# Generated by Django 3.2.16 on 2022-12-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221213_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
