# Generated by Django 3.2.16 on 2023-01-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230106_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
